# Generated by Django 3.1.4 on 2020-12-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_clase_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='clase',
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.materia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha_clase',
            field=models.DateField(),
        ),
    ]
